version: '3'
services:
  subscriber:
    container_name: subscriber
    volumes:
      - uploads:/subscriber/uploads
    build: ./subscriber
    working_dir: /subscriber/
    command: bash -c './run_service.sh'
    ports:
      - 80:5000
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@34.27.245.68/tasks
      AUTH_SERVICE: http://auth-microservice:5000
      UPLOAD_FOLDER: /subscriber/uploads
      PYTHONUNBUFFERED: 1
      CELERY_BROKER: redis://redis:6379/0
      GCP_PROJECT_ID: hybrid-circle-368300
      GCP_SUBSCRIPTION_ID: cloud-convertion-topic-sub
      GCP_SUBSCRIBE_TIMEOUT: 5.0

volumes:
  uploads:
