services:

  # Users Microservice
  users-microservice:
    volumes:
      - ./users/:/mnt/
    build: ./users
    working_dir: /users_microservice/
    command: bash -c 'while !</dev/tcp/users-database/5432; do sleep 1; done; gunicorn -b 0.0.0.0:5000 app:app'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@users-database/users
    ports:
      - '5000:5000'
    links: 
      - users-database

  users-database:
    image:
      postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - '5432:5432'
    volumes:
      - ./users/:/db/

  # Tasks Microservice
  tasks-microservice:
    volumes:
      - ./tasks/:/mnt/
    build: ./tasks
    working_dir: /tasks_microservice/
    command: bash -c 'while !</dev/tcp/tasks-database/5432; do sleep 1; done; gunicorn -b 0.0.0.0:5000 app:app'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@tasks-database/tasks
    ports:
      - '5001:5000'
    depends_on: 
      - tasks-database

  tasks-database:
    image:
      postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    ports:
      - '5434:5432'
    volumes:
      - ./tasks/:/db/

  # Auth Microservice
  auth-microservice:
    volumes:
      - ./auth/:/mnt/
    build: ./tasks
    working_dir: /auth_microservice/
    command: bash -c 'while !</dev/tcp/auth-database/5432; do sleep 1; done; gunicorn -b 0.0.0.0:5000 app:app'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@auth-database/auth
    ports:
      - '5002:5000'
    depends_on: 
      - auth-database

  auth-database:
    image:
      postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - '5436:5432'
    volumes:
      - ./auth/:/db/

  # Files Microservice
  files-microservice:
    volumes:
      - ./files/:/mnt/
    build: ./files
    working_dir: /files_microservice/
    command: bash -c 'while !</dev/tcp/files-database/5432; do sleep 1; done; gunicorn -b 0.0.0.0:5000 app:app'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@files-database/files
    ports:
      - '5003:5000'
    depends_on: 
      - files-database

  files-database:
    image:
      postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=files
    ports:
      - '5438:5432'
    volumes:
      - ./files/:/db/
