services:

  # Auth Microservice
  auth-microservice:
    container_name: auth-microservice
    volumes:
      - ./auth/:/mnt/
    build: ./auth
    working_dir: /auth_microservice/
    command: bash -c './run_service.sh'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@auth-database/auth
      JWT_SECRET_KEY: 7b11677e262b608e88ee6747372a1776
    
    depends_on: 
      - auth-database

  auth-database:
    container_name: auth-database
    image:
      postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - '5432:5432'
    volumes:
      - ./auth/:/db/

  # Tasks Microservice
  tasks-microservice:
    container_name: tasks-microservice
    volumes:
      - ./tasks/:/mnt/
    build: ./tasks
    working_dir: /tasks_microservice/
    command: bash -c './run_service.sh'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@tasks-database/tasks
      FILES_MICROSERVICE: http://files-microservice:5000
      CELERY_BROKER: redis://redis:6379/0
    depends_on: 
      - tasks-database

  tasks-database:
    container_name: tasks-database
    image:
      postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=tasks
    ports:
      - '5434:5432'
    volumes:
      - ./tasks/:/db/

  # Files Microservice
  files-microservice:
    container_name: files-microservice
    volumes:
      - ./files/:/mnt/
    build: ./files
    working_dir: /files_microservice/
    command: bash -c './run_service.sh'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@files-database/files
      CELERY_BROKER: redis://redis:6379/0
    depends_on:
      - redis
          

  redis:
    image: redis

  nginx:
    ports:
      - 3000:80
    build: ./nginx
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - auth-microservice
