version: '3'
services:
  auth-microservice:
    container_name: auth-microservice
    volumes:
      - ./auth/:/mnt/
    build: ./auth
    working_dir: /auth_microservice/
    command: bash -c './run_service.sh'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@34.121.35.36/auth
      JWT_SECRET_KEY: 7b11677e262b608e88ee6747372a1776


  tasks-microservice:
    container_name: tasks-microservice
    volumes:
      - uploads:/tasks_microservice/nfs/
    build: ./tasks
    working_dir: /tasks_microservice/
    command: bash -c './run_service.sh'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@34.121.35.36/tasks
      AUTH_SERVICE: http://auth-microservice:5000
      UPLOAD_FOLDER: /tasks_microservice/
      PYTHONUNBUFFERED: 1

  nginx:
    ports:
      - 3000:80
    build: ./nginx
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - auth-microservice
        - tasks-microservice
volumes:
  uploads:
