services:

  # Auth Microservice
  auth-microservice:
    container_name: auth-microservice
    volumes:
      - ./auth/:/mnt/
    build: ./auth
    working_dir: /auth_microservice/
    command: bash -c 'while !</dev/tcp/auth-database/5432; do sleep 5; done; gunicorn -b 0.0.0.0:5000 app:app'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@auth-database/auth
    ports:
      - '5002:5000'
    depends_on: 
      - auth-database

  auth-database:
    container_name: auth-database
    image:
      postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth
    ports:
      - '5436:5432'
    volumes:
      - ./auth/:/db/

  # Users Microservice
  users-microservice:
    container_name: users-microservice
    volumes:
      - ./users/:/mnt/
    build: ./users
    working_dir: /users_microservice/
    command: bash -c 'while !</dev/tcp/users-database/5432; do sleep 1; done; gunicorn -b 0.0.0.0:5000 app:app'
    environment:
      DATABASE_URL: postgresql+psycopg2://postgres:postgres@users-database/users
      AUTH_SERVICE_URL: http://auth-microservice:5000
    ports:
      - '5000:5000'
    depends_on: 
      - users-database
    links:
      - auth-microservice

  users-database:
    container_name: users-database
    image:
      postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=users
    ports:
      - '5432:5432'
    volumes:
      - ./users/:/db/

  nginx:
    ports:
      - 3000:80
    build: ./nginx
    volumes:
        - ./nginx/nginx-proxy.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
        - auth-microservice
        - users-microservice
